#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_MAY         0
#define MUGSHOT_SIDNEY      1
#define MUGSHOT_PHOEBE      2
#define MUGSHOT_GLACIA      3
#define MUGSHOT_DRAKE       4
#define MUGSHOT_CHAMPION    5

#define MUGSHOTS_COUNT      6

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H
